### ISSUE TITLE
Needed: System Settings Default for Airplane Mode Radios

### ISSUE THREAD

**Issue by topherwhite** [rfcx/guardian-opi-android-source#9]
By default, the system settings for airplane mode include wifi in the list of radios to enable/disable. 
This leads to a the hotspot being disabled on first boot.
To fix this, we need the system settings to exclude wifi from the list of radios affected by airplane mode:

`settings/global/airplane_mode_radios —> cell,bluetooth,nfc,wimax`

Feel free to ask Topher if you're not sure what is needed here. This is a needed feature for version 0.2.2 this week.

**Comment by Tooseriuz** [comment]
Fix released in v0.2.2
